#!/bin/sh

#
# Add someone into the phonebook
#

echo "Type in your new entry."
echo "When you are done, just type a single"
echo "RETURN on the line."
first=
entry=

while true
do
  echo -n ">> "
  read line

  if [ -n "$line" ]
  then
    entry="$entry$line^"

    if [ -z "$first" ]
    then
      first=$line
    fi
  else
    break
  fi
done
echo "$entry" >> $PHONEBOOK
sort -o $PHONEBOOK $PHONEBOOK
echo
echo "$first has been added to the phone book."
