#!/bin/sh
install=""
until [ -n "$install" ]
do
  echo "Do you want to install in your home directory,$HOME?(y/n)"
  read answer
  case $answer in
    y) install=$HOME;;
    n) echo "Where do you want to install?"
       read "install";;
    *) echo "Bad choice"
  esac
done

if [ ! -d "$install" ]
then
  echo "$install does not exist."
else
  if [ -d "$install/mail" ]
  then
    echo "$install/mail already exists."
  else

mkdir "$install/mail/"
mkdir "$install/mail/files"
mkdir "$install/mail/programs"
#programs/showmail
echo '#!/bin/bash
name="$1"
home="$2"
echo "_______
Unread |
-----------------------------------------------"
cd "$home"/mail/users/$name/unread
if [ `ls | grep "txt~"` ]
then
  rm `ls | grep "txt~"`
fi
ls -1 "$home"/mail/users/$name/unread
echo "_____
Read |
-----------------------------------------------"
ls -1 "$home"/mail/users/$name/read' > "$install/mail/programs/showmail"
chmod 755 "$install/mail/programs/showmail"

#programs/sendmail
echo '#!/bin/bash
name="$1"
person="$2"
home="$3"

if [ -d "$home/mail/users/$person/unread" ]
then
  goodchoice=""
  clear
  until [ "$goodchoice" = "true" ]
  do
    cd "$home/mail/users/$person/unread"
    echo -n "subject?"
    read subject
    filename=`echo -n "$subject" | tr " " "_"`

    if [ -f "$home/mail/users/$person/unread/$subject" ]
    then
      clear
      echo "$subject already exists!"
    else
      if [ -n "$subject" ]
      then
        echo "




--$name" > "$filename"
        gedit --new-window "$filename"
        goodchoice="true"
        echo `date`":	$subject sent from $name to $person" >> "$home"/mail/files/log.txt
      else
        clear
      fi
    fi
  done
else
  clear
  echo "$person does not exist"
  read a
fi' > "$install/mail/programs/sendmail"
chmod 755 "$install/mail/programs/sendmail"

#programs/checkmail
echo '#!/bin/bash
name="$1"
home="$2"

maildir="$home/mail/users/$name"

echo "Which mail do you want to read?"
"$home"/mail/programs/showmail "$name" "$home"
read file
echo
if [ -f "$maildir/unread/$file" ]
then
  clear
  file="$maildir/unread/$file"
  echo "--------------------------------------"
  cat "$file"
  echo "--------------------------------------"
  echo `date`":	"`basename $file`" read by $name" >> "$home"/mail/files/log.txt
  mv "$file" "$maildir/read/"
elif [ -f "$maildir/read/$file" ]
then
  clear
  file="$maildir/read/$file"
  echo "--------------------------------------"
  cat "$file"
  echo "--------------------------------------"
  echo `date`":	"`basename $file`" read by $name" >> "$home"/mail/files/log.txt
else
  if [ -n "$file" ]
  then
    file=`basename $file`
  fi
  clear
  echo "$file does not exist."
fi

read a' > "$install/mail/programs/checkmail"
chmod 755 "$install/mail/programs/checkmail"

#programs/startmail
echo '#!/bin/bash
home="$1"
if [ ! -d "$home/mail/users" ]
then
  mkdir mail/users
fi
echo -n "Select a name or choose a new name:
"
ls -1 "$home"/mail/users
echo
read name
if [ ! -n "$name" ]
then
  name=User
fi
name=`echo "$name" | tr " " "_"`
maildir="$home/mail/users/$name"
if [ ! -d "$maildir" ]
then
  mkdir "$maildir"
  cd "$maildir"
  mkdir "read" "unread"
  cd "$home"
  echo "New password for $name:"
  read password
  password=`echo "$password" | rev`
  perl -e mc2tpq3tnuvpqb834tow43t8bwpb6t8mb7p34tv23vpqbn438print unpack "H*", "mc2tpq3tnuvpqb834tow43t8bwpb6t8mb7p34tv23vpqbn438"$password\"" | rev > "$maildir/.password"
else
  echo "Password for $name:"
  read password
  password=`echo "$password" | rev`
  password=`perl -e mc2tpq3tnuvpqb834tow43t8bwpb6t8mb7p34tv23vpqbn438print unpack "H*", "mc2tpq3tnuvpqb834tow43t8bwpb6t8mb7p34tv23vpqbn438"$password\"" | rev`
  correct=`cat $maildir/.password`
  if [ "$password" != "$correct" ]
  then
    echo "Incorrect Password."
    > "$home"/mail/files/name.txt
    echo `date`":	Failed Password for $name" >> "$home"/mail/files/log.txt
    echo `date`":	Failed Password Attempt: $password" > "$maildir/unread/$RANDOM"
    exit 1
  fi
fi
echo $name > "$home"/mail/files/name.txt
echo `date`":	Logged in as $name" >> "$home"/mail/files/log.txt' | sed "s/mc2tpq3tnuvpqb834tow43t8bwpb6t8mb7p34tv23vpqbn438/'/g" > "$install/mail/programs/startmail"
chmod 755 "$install/mail/programs/startmail"

#programs/mailprog
echo '#!/bin/bash
echo "
 ___      ___       __       _____   _
|   \    /   |     /  \     |_   _| | |
| |\ \  / /| |    / /\ \      | |   | |
| | \ \/ / | |   / /__\ \     | |   | |
| |  \__/  | |  / ______ \   _| |_  | |____
|_|        | | /_/      \_\ |_____| |______|
"

sleep 2
home='"$install"'
name=""
while [ "$name" == "" ]
do
  clear
  "$home"/mail/programs/startmail "$home"
  name=`cat "$home"/mail/files/name.txt`
done
while true
do
  clear
  echo "
============================
=               _____      =
= |\  /|   /\     |   |    =
= | \/ |  /__\    |   |    =
= |    | /    \ __|__ |___ =
=                          =
============================"
  echo "User: " $name
  echo "Mail:"
  "$home"/mail/programs/showmail "$name" "$home"
  echo "==============================================="
  echo "What do you want to do(1-5)?"
  echo "1.Send a message to any user."
  echo "2.Read a message in your inbox."
  echo "3.Log out of your account."
  echo "4.List all the users."
  echo "5.exit."
  read choice
  cd
  case "$choice" in
    1) clear
       echo "Choose a person:"
       ls -1 "$home"/mail/users
       echo
       read person
       "$home"/mail/programs/sendmail "$name" "$person" "$home";;
    2) clear
       "$home"/mail/programs/checkmail "$name" "$home";;
    3) clear
       echo `date`":	Logged out form $name" >> "$home"/mail/files/log.txt
       name=""
       while [ "$name" == "" ]
       do
         clear
         "$home"/mail/programs/startmail "$home"
         name=`cat "$home"/mail/files/name.txt`
       done;;
    4) clear
       ls -1 "$home"/mail/users
       read a;;
    5) echo `date`":	Logged out form $name" >> "$home"/mail/files/log.txt
       echo `date`":	Exited" >> "$home"/mail/files/log.txt
       exit;;
    5) more "$home"/mail/files/log.txt;;
  esac
done' > "$install/mail/programs/mailprog"
chmod 755 "$install/mail/programs/mailprog"

#mailprog.desktop
echo '#!/usr/bin/env xdg-open

[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Terminal=true
Icon[en_US]=gnome-panel-launcher
Name[en_US]=Mail Program
Exec='"$install"'/mail/programs/mailprog
Name=Mail Program
Icon=gnome-panel-launcher

' > "$install/mail/mailprog.desktop"
chmod 755 "$install/mail/mailprog.desktop"

mkdir "$install/mail/users"
#read.txt
echo 'Run '"$install"'/mail/Mail Program to start.
Delete '"$install"'/mail to uninstall

' > "$install/mail/read.txt"
chmod 755 "$install/mail/read.txt"


    echo "Installation has been successfully completed."
  fi
fi
echo "Press ENTER to exit."
read a

